<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-8LLUNH4" failures="1" tests="2" name="Test" time="23.316" errors="0" timestamp="2023-05-06T13:58:58 IST">
  <testcase classname="TESTCASE.VerifySignUp" name="signup" time="7.987"/>
  <testcase classname="TESTCASE.VerifyLogin" name="login1" time="0.724">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	error message is not valid expected [Please check your username and password. If you still can&amp;apos;t log in, contact your Salesforce administrator.] but found []">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
error message is not valid expected [Please check your username and password. If you still can't log in, contact your Salesforce administrator.] but found []
at RESOURCES.CommonMethods.handleAssertions(CommonMethods.java:23)
at TESTCASE.VerifyLogin.login1(VerifyLogin.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login1 -->
</testsuite> <!-- Test -->
